[tox]
env_list =
    markdown-lint
minversion = 4.30.2

[testenv]
description = run the tests with pytest
skip_install = True
allowlist_externals =
    gem
    mdl
commands_pre =
    gem install --no-document --install-dir {env_dir}/install --bindir {env_dir}/bin mdl
commands =
    {env_dir}/bin/mdl {posargs:python/ fedora/ quayio/}
